"""add_unique_constraints_for_products

Revision ID: 0b6eca6fd5da
Revises: a0614c3af295
Create Date: 2025-09-29 18:27:38.558098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6eca6fd5da'
down_revision: Union[str, Sequence[str], None] = 'a0614c3af295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint for store_id + sku combination
    op.create_unique_constraint(
        "uq_products_store_sku", 
        "products", 
        ["store_id", "sku"]
    )
    
    # Add unique constraint for asin + marketplace_id combination  
    op.create_unique_constraint(
        "uq_products_asin_marketplace", 
        "products", 
        ["asin", "marketplace_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraints
    op.drop_constraint("uq_products_asin_marketplace", "products", type_="unique")
    op.drop_constraint("uq_products_store_sku", "products", type_="unique")
    # ### end Alembic commands ###
