"""add_spapi_fields_to_models

Revision ID: 3f309d107c2c
Revises: 3b7cd91516a5
Create Date: 2025-09-29 17:48:36.404692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f309d107c2c'
down_revision: Union[str, Sequence[str], None] = '3b7cd91516a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('condition_type', sa.String(length=32), nullable=False))
    op.add_column('products', sa.Column('min_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('max_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('repricing_enabled', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('last_repriced_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'])
    op.add_column('stores', sa.Column('refresh_token', sa.Text(), nullable=False))
    op.add_column('stores', sa.Column('store_name', sa.String(length=255), nullable=False))
    op.add_column('stores', sa.Column('seller_id', sa.String(length=64), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('stores', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('stores', 'lwa_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('lwa_refresh_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('stores', 'created_at')
    op.drop_column('stores', 'last_sync')
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'seller_id')
    op.drop_column('stores', 'store_name')
    op.drop_column('stores', 'refresh_token')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'last_repriced_at')
    op.drop_column('products', 'repricing_enabled')
    op.drop_column('products', 'max_price')
    op.drop_column('products', 'min_price')
    op.drop_column('products', 'condition_type')
    op.drop_column('products', 'store_id')
    # ### end Alembic commands ###
