"""enhance_product_model_for_amazon_integration

Revision ID: a0614c3af295
Revises: 7474404902c6
Create Date: 2025-09-29 18:16:34.513282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0614c3af295'
down_revision: Union[str, Sequence[str], None] = '7474404902c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('marketplace_id', sa.String(length=16), nullable=False))
    op.add_column('products', sa.Column('product_type', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('listing_status', sa.String(length=32), nullable=False))
    op.add_column('products', sa.Column('fulfillment_channel', sa.String(length=8), nullable=False))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=128), nullable=True))
    op.add_column('products', sa.Column('manufacturer', sa.String(length=128), nullable=True))
    op.add_column('products', sa.Column('product_image_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('item_weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('item_length', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('item_width', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('item_height', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('sync_status', sa.String(length=16), nullable=False))
    op.add_column('products', sa.Column('sync_error_message', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'sync_error_message')
    op.drop_column('products', 'sync_status')
    op.drop_column('products', 'last_synced_at')
    op.drop_column('products', 'item_height')
    op.drop_column('products', 'item_width')
    op.drop_column('products', 'item_length')
    op.drop_column('products', 'item_weight')
    op.drop_column('products', 'product_image_url')
    op.drop_column('products', 'manufacturer')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'description')
    op.drop_column('products', 'fulfillment_channel')
    op.drop_column('products', 'listing_status')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'marketplace_id')
    # ### end Alembic commands ###
