"""Add subscription fields to User model

Revision ID: bff8a1847f3f
Revises: fix_asin_constraint
Create Date: 2025-11-14 05:10:34.711067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff8a1847f3f'
down_revision: Union[str, Sequence[str], None] = 'fix_asin_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('subscription_period_end', sa.DateTime(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET subscription_plan = 'free' WHERE subscription_plan IS NULL")
    op.execute("UPDATE users SET subscription_status = 'active' WHERE subscription_status IS NULL")
    
    # Now make columns non-nullable
    op.alter_column('users', 'subscription_plan', nullable=False)
    op.alter_column('users', 'subscription_status', nullable=False)
    
    # Add unique constraints
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'subscription_period_end')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###
